{
	"version": 1561476194,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/ride1-sheet0.png",
		"images/ride1-sheet1.png",
		"images/road.png",
		"images/grass.png",
		"images/wall-sheet0.png",
		"images/blueseparator-sheet0.png",
		"images/checkmark1-sheet0.png",
		"images/checkmark1-sheet1.png",
		"images/checkmark1-sheet2.png",
		"images/checkmark2-sheet0.png",
		"images/checkmark2-sheet1.png",
		"images/ride2-sheet0.png",
		"images/ride2-sheet1.png",
		"images/grasslarge-sheet0.png",
		"images/ride3-sheet0.png",
		"images/ride4-sheet0.png",
		"images/ride4-sheet1.png",
		"images/ride5-sheet0.png",
		"images/ride5-sheet1.png",
		"images/castle-sheet0.png",
		"images/castle-sheet1.png",
		"images/ride6-sheet0.png",
		"images/ride6-sheet1.png",
		"images/ride7-sheet0.png",
		"images/ride7-sheet1.png",
		"images/ride8-sheet0.png",
		"images/ride8-sheet1.png",
		"images/ride9-sheet0.png",
		"images/ride10-sheet0.png",
		"images/ride10-sheet1.png",
		"images/ride11-sheet0.png",
		"images/ride11-sheet1.png",
		"images/notebookbackground-sheet0.png",
		"images/tooltipcloud-sheet0.png",
		"images/tree1-sheet0.png",
		"images/bush1-sheet0.png",
		"images/tree2-sheet0.png",
		"images/bush2-sheet0.png",
		"images/bush3-sheet0.png",
		"images/tree3-sheet0.png",
		"images/completedmark-sheet0.png",
		"images/blueframe1-sheet0.png",
		"images/footstepparticles.png",
		"images/fireworkpurple.png",
		"images/fireworkblue.png",
		"images/fireworkgreen.png",
		"images/fireworkred.png",
		"images/door-sheet0.png",
		"images/door-sheet1.png",
		"images/door-sheet2.png",
		"images/flag-sheet0.png",
		"images/spritefont.png",
		"images/difficultychillis-sheet0.png",
		"images/connectingline-sheet0.png",
		"images/questionimage-sheet0.png",
		"images/badge-sheet0.png",
		"images/bulletdot-sheet0.png",
		"images/rulerangle-sheet0.png",
		"images/rulerdistance-sheet0.png",
		"images/rulerline1-sheet0.png",
		"images/rulerdot1-sheet0.png",
		"images/rulerdot2-sheet0.png",
		"images/ride12-sheet0.png",
		"images/ride12-sheet1.png",
		"images/ride14-sheet0.png",
		"images/ride15-sheet0.png",
		"images/ride16-sheet0.png",
		"images/ride16-sheet1.png",
		"images/ride17-sheet0.png",
		"images/ride18-sheet0.png",
		"images/ride19-sheet0.png",
		"images/ride20-sheet0.png",
		"images/ride20-sheet1.png",
		"images/ride13-sheet0.png",
		"images/ride13-sheet1.png",
		"images/greylayout-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/icon1-sheet0.png",
		"images/icon2-sheet0.png",
		"images/icon3-sheet0.png",
		"images/icon4-sheet0.png",
		"images/icon5-sheet0.png",
		"images/icon6-sheet0.png",
		"images/icon7-sheet0.png",
		"images/icon8-sheet0.png",
		"images/icon9-sheet0.png",
		"images/icon10-sheet0.png",
		"images/icon11-sheet0.png",
		"images/icon12-sheet0.png",
		"images/icon13-sheet0.png",
		"images/icon14-sheet0.png",
		"images/icon15-sheet0.png",
		"images/icon16-sheet0.png",
		"images/icon17-sheet0.png",
		"images/icon18-sheet0.png",
		"images/icon19-sheet0.png",
		"images/icon20-sheet0.png",
		"media/footstep1.m4a",
		"media/footstep1.ogg",
		"media/footstep2.m4a",
		"media/footstep2.ogg",
		"media/correctanswer.m4a",
		"media/correctanswer.ogg",
		"media/error.m4a",
		"media/error.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/goback.m4a",
		"media/goback.ogg",
		"media/successjingle.m4a",
		"media/successjingle.ogg",
		"media/yay.m4a",
		"media/yay.ogg",
		"media/firework1.m4a",
		"media/firework1.ogg",
		"media/firework2.m4a",
		"media/firework2.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"anglesq1.png",
		"anglesq2.png",
		"anglesq3.png",
		"anglesq4.png",
		"anglesq5.png",
		"anglesq6.png",
		"anglesq7.png",
		"anglesq8.png",
		"anglesq9.png",
		"anglesq10.png",
		"anglesq11.png",
		"anglesq12.png",
		"anglesq13.png",
		"anglesq14.png",
		"anglesq15.png",
		"anglesq16.png",
		"anglesq17.png",
		"anglesq18.png",
		"parallelogramq2.png",
		"parallelogramq3.png",
		"parallelogramq4.png",
		"parallelogramq5.png",
		"parallelogramq6.png",
		"parallelogramq7.png",
		"parallelogramq8.png",
		"parallelogramq9.png",
		"parallelogramq10.png",
		"parallelogramq11.png",
		"parallelogramq12.png",
		"parallelogramq13.png",
		"parallelogramq14.png",
		"parallelogramq15.png",
		"parallelogramq16.png",
		"parallelogramareaq1.png",
		"parallelogramareaq2.png",
		"parallelogramareaq3.png",
		"parallelogramareaq4.png",
		"parallelogramareaq5.png",
		"parallelogramareaq6.png",
		"parallelogramareaq7.png",
		"parallelogramareaq8.png",
		"parallelogramareaq9.png",
		"parallelogramareaq10.png",
		"parallelogramareaq11.png",
		"parallelogramareaq12.png",
		"parallelogramareaq13.png",
		"parallelogramareaq14.png",
		"parallelogramareaq15.png",
		"parallelogramareaq16.png",
		"parallelogramheightq1.png",
		"parallelogramheightq2.png",
		"parallelogramheightq3.png",
		"parallelogramheightq4.png",
		"parallelogramheightq5.png",
		"parallelogramheightq6.png",
		"parallelogramheightq7.png",
		"parallelogramheightq8.png",
		"parallelogramheightq9.png",
		"parallelogramheightq10.png",
		"parallelogramheightq11.png",
		"parallelogramheightq12.png",
		"parallelogramheightq13.png",
		"rectangleq1.png",
		"rectangleq2.png",
		"rectangleq3.png",
		"rectangleq5.png",
		"rectangleq6.png",
		"rectangleq7.png",
		"rectangleq8.png",
		"rectangleq9.png",
		"rhombusq1.png",
		"rhombusq2.png",
		"rhombusq4.png",
		"rhombusq5.png",
		"rhombusq6.png",
		"rhombusq7.png",
		"rhombusq8.png",
		"rhombusq9.png",
		"rhombusq10.png",
		"rhombusq11.png",
		"rhombusq12.png",
		"rhombusq13.png",
		"rhombusq14.png",
		"rhombusq15.png",
		"rhombusq16.png",
		"rhombusq17.png",
		"rhombusq18.png",
		"rhombusq19.png",
		"rhombusq20.png",
		"rhombusq21.png",
		"rhombusq22.png",
		"rhombusq23.png",
		"rhombusq24.png",
		"rhombusq25.png",
		"rhombusq26.png",
		"squareq15.png",
		"squareq16.png",
		"squareq17.png",
		"squareq20.png",
		"triangleareaq1.png",
		"triangleareaq2.png",
		"triangleareaq3.png",
		"triangleareaq4.png",
		"triangleareaq5.png",
		"triangleareaq6.png",
		"triangleareaq7.png",
		"triangleareaq8.png",
		"triangleareaq9.png",
		"triangleareaq10.png",
		"triangleareaq11.png",
		"triangleareaq12.png",
		"triangleareaq13.png",
		"triangleareaq14.png",
		"triangleareaq15.png",
		"triangleareaq16.png",
		"triangleareaq17.png",
		"triangleareaq18.png",
		"triangleareaq19.png",
		"triangleareaq20.png",
		"triangleareaq21.png",
		"triangleareaq22.png",
		"triangleheightq1.png",
		"triangleheightq2.png",
		"triangleheightq3.png",
		"triangleheightq4.png",
		"triangleheightq5.png",
		"triangleheightq6.png",
		"triangleheightq7.png",
		"triangleheightq8.png",
		"triangleheightq9.png",
		"triangleheightq10.png",
		"triangleheightq11.png",
		"triangleheightq12.png",
		"triangleheightq13.png",
		"triangleheightq14.png",
		"triangleheightq15.png",
		"triangleheightq16.png",
		"triangleheightq17.png",
		"edgesq1.png",
		"edgesq2.png",
		"edgesq3.png",
		"edgesq4.png",
		"edgesq5.png",
		"edgesq6.png",
		"edgesq7.png",
		"edgesq8.png",
		"edgesq9.png",
		"edgesq10.png",
		"edgesq11.png",
		"edgesq12.png",
		"edgesq13.png",
		"edgesq14.png",
		"edgesq15.png",
		"edgesq16.png",
		"edgesq17.png",
		"edgesq18.png",
		"edgesq19.png",
		"edgesq20.png",
		"edgesq21.png",
		"edgesq22.png",
		"edgesq23.png",
		"addsubq1.png",
		"addsubq2.png",
		"addsubq3.png",
		"addsubq4.png",
		"addsubq5.png",
		"addsubq6.png",
		"addsubq7.png",
		"addsubq8.png",
		"addsubq9.png",
		"addsubq10.png",
		"addsubq11.png",
		"addsubq12.png",
		"addsubq13.png",
		"addsubq14.png",
		"addsubq15.png",
		"addsubq16.png",
		"addsubq17.png",
		"addsubq18.png",
		"addsubq19.png",
		"addsubq20.png",
		"addsubq21.png",
		"addsubq22.png",
		"addsubq23.png",
		"addsubq24.png",
		"addsubq25.png",
		"addsubq26.png",
		"addsubq27.png",
		"addsubq28.png",
		"area11.png",
		"area12.png",
		"area13.png",
		"area14.png",
		"area15.png",
		"area16.png",
		"area25.png",
		"area26.png",
		"area27.png",
		"area28.png",
		"compareq1.png",
		"compareq2.png",
		"compareq3.png",
		"compareq4.png",
		"compareq5.png",
		"compareq6.png",
		"compareq7.png",
		"compareq8.png",
		"compareq9.png",
		"compareq10.png",
		"compareq11.png",
		"compareq12.png",
		"compareq13.png",
		"compareq14.png",
		"compareq15.png",
		"compareq16.png",
		"compareq17.png",
		"compareq18.png",
		"compareq19.png",
		"compareq20.png",
		"compareq21.png",
		"compareq22.png",
		"compareq23.png",
		"compareq24.png",
		"compareq25.png",
		"compareq26.png",
		"compareq27.png",
		"compareq28.png",
		"compareq29.png",
		"compareq30.png",
		"compareq31.png",
		"compareq32.png",
		"compareq33.png",
		"perimeter1.png",
		"perimeter2.png",
		"perimeter3.png",
		"perimeter4.png",
		"perimeter5.png",
		"perimeter6.png",
		"perimeter7.png",
		"perimeter8.png",
		"perimeter9.png",
		"perimeter10.png",
		"perimeter11.png",
		"perimeter12.png",
		"perimeter13.png",
		"perimeter14.png",
		"perimeter15.png",
		"perimeter16.png",
		"perimeter17.png",
		"perimeter18.png",
		"perimeter19.png",
		"perimeter20.png",
		"perimeter21.png",
		"perimeter22.png",
		"perimeter23.png",
		"perimeter24.png",
		"perimeter25.png",
		"perimeter26.png",
		"perimeter27.png",
		"perimeter28.png",
		"גובה במשולשeasy_1_1.txt",
		"גובה במשולשeasy_2_1.txt",
		"גובה במשולשeasy_2_2.txt",
		"גובה במשולשeasy_3_1.txt",
		"גובה במשולשeasy_3_2.txt",
		"גובה במשולשeasy_3_3.txt",
		"גובה במשולשeasy_4_1.txt",
		"גובה במשולשeasy_4_2.txt",
		"גובה במשולשeasy_4_3.txt",
		"גובה במשולשeasy_4_4.txt",
		"גובה במשולשhard_1_1.txt",
		"גובה במשולשhard_2_1.txt",
		"גובה במשולשhard_2_2.txt",
		"גובה במשולשhard_3_1.txt",
		"גובה במשולשhard_3_2.txt",
		"גובה במשולשhard_3_3.txt",
		"גובה במשולשhard_4_1.txt",
		"גובה במשולשhard_4_2.txt",
		"גובה במשולשhard_4_3.txt",
		"גובה במשולשhard_4_4.txt",
		"האלפית כמספר עשרוניeasy_1_1.txt",
		"האלפית כמספר עשרוניeasy_2_1.txt",
		"האלפית כמספר עשרוניeasy_2_2.txt",
		"האלפית כמספר עשרוניeasy_3_1.txt",
		"האלפית כמספר עשרוניeasy_3_2.txt",
		"האלפית כמספר עשרוניeasy_3_3.txt",
		"האלפית כמספר עשרוניeasy_4_1.txt",
		"האלפית כמספר עשרוניeasy_4_2.txt",
		"האלפית כמספר עשרוניeasy_4_3.txt",
		"האלפית כמספר עשרוניeasy_4_4.txt",
		"האלפית כמספר עשרוניhard_1_1.txt",
		"האלפית כמספר עשרוניhard_2_1.txt",
		"האלפית כמספר עשרוניhard_2_2.txt",
		"האלפית כמספר עשרוניhard_3_1.txt",
		"האלפית כמספר עשרוניhard_3_2.txt",
		"האלפית כמספר עשרוניhard_3_3.txt",
		"האלפית כמספר עשרוניhard_4_1.txt",
		"האלפית כמספר עשרוניhard_4_2.txt",
		"האלפית כמספר עשרוניhard_4_3.txt",
		"האלפית כמספר עשרוניhard_4_4.txt",
		"היקף מצולעeasy_1_1.txt",
		"היקף מצולעeasy_2_1.txt",
		"היקף מצולעeasy_2_2.txt",
		"היקף מצולעeasy_3_1.txt",
		"היקף מצולעeasy_3_2.txt",
		"היקף מצולעeasy_3_3.txt",
		"היקף מצולעeasy_4_1.txt",
		"היקף מצולעeasy_4_2.txt",
		"היקף מצולעeasy_4_3.txt",
		"היקף מצולעeasy_4_4.txt",
		"היקף מצולעhard_1_1.txt",
		"היקף מצולעhard_2_1.txt",
		"היקף מצולעhard_2_2.txt",
		"היקף מצולעhard_3_1.txt",
		"היקף מצולעhard_3_2.txt",
		"היקף מצולעhard_3_3.txt",
		"היקף מצולעhard_4_1.txt",
		"היקף מצולעhard_4_2.txt",
		"היקף מצולעhard_4_3.txt",
		"היקף מצולעhard_4_4.txt",
		"המאית כמספר עשרוניeasy_1_1.txt",
		"המאית כמספר עשרוניeasy_2_1.txt",
		"המאית כמספר עשרוניeasy_2_2.txt",
		"המאית כמספר עשרוניeasy_3_1.txt",
		"המאית כמספר עשרוניeasy_3_2.txt",
		"המאית כמספר עשרוניeasy_3_3.txt",
		"המאית כמספר עשרוניeasy_4_1.txt",
		"המאית כמספר עשרוניeasy_4_2.txt",
		"המאית כמספר עשרוניeasy_4_3.txt",
		"המאית כמספר עשרוניeasy_4_4.txt",
		"המאית כמספר עשרוניhard_1_1.txt",
		"המאית כמספר עשרוניhard_2_1.txt",
		"המאית כמספר עשרוניhard_2_2.txt",
		"המאית כמספר עשרוניhard_3_1.txt",
		"המאית כמספר עשרוניhard_3_2.txt",
		"המאית כמספר עשרוניhard_3_3.txt",
		"המאית כמספר עשרוניhard_4_1.txt",
		"המאית כמספר עשרוניhard_4_2.txt",
		"המאית כמספר עשרוניhard_4_3.txt",
		"המאית כמספר עשרוניhard_4_4.txt",
		"העשירית כמספר עשרוניeasy_1_1.txt",
		"העשירית כמספר עשרוניeasy_2_1.txt",
		"העשירית כמספר עשרוניeasy_2_2.txt",
		"העשירית כמספר עשרוניeasy_3_1.txt",
		"העשירית כמספר עשרוניeasy_3_2.txt",
		"העשירית כמספר עשרוניeasy_3_3.txt",
		"העשירית כמספר עשרוניeasy_4_1.txt",
		"העשירית כמספר עשרוניeasy_4_2.txt",
		"העשירית כמספר עשרוניeasy_4_3.txt",
		"העשירית כמספר עשרוניeasy_4_4.txt",
		"העשירית כמספר עשרוניhard_1_1.txt",
		"העשירית כמספר עשרוניhard_2_1.txt",
		"העשירית כמספר עשרוניhard_2_2.txt",
		"העשירית כמספר עשרוניhard_3_1.txt",
		"העשירית כמספר עשרוניhard_3_2.txt",
		"העשירית כמספר עשרוניhard_3_3.txt",
		"העשירית כמספר עשרוניhard_4_1.txt",
		"העשירית כמספר עשרוניhard_4_2.txt",
		"העשירית כמספר עשרוניhard_4_3.txt",
		"העשירית כמספר עשרוניhard_4_4.txt",
		"הריבוע מקבילית מיוחדתeasy_1_1.txt",
		"הריבוע מקבילית מיוחדתeasy_2_1.txt",
		"הריבוע מקבילית מיוחדתeasy_2_2.txt",
		"הריבוע מקבילית מיוחדתeasy_3_1.txt",
		"הריבוע מקבילית מיוחדתeasy_3_2.txt",
		"הריבוע מקבילית מיוחדתeasy_3_3.txt",
		"הריבוע מקבילית מיוחדתeasy_4_1.txt",
		"הריבוע מקבילית מיוחדתeasy_4_2.txt",
		"הריבוע מקבילית מיוחדתeasy_4_3.txt",
		"הריבוע מקבילית מיוחדתeasy_4_4.txt",
		"הריבוע מקבילית מיוחדתhard_1_1.txt",
		"הריבוע מקבילית מיוחדתhard_2_1.txt",
		"הריבוע מקבילית מיוחדתhard_2_2.txt",
		"הריבוע מקבילית מיוחדתhard_3_1.txt",
		"הריבוע מקבילית מיוחדתhard_3_2.txt",
		"הריבוע מקבילית מיוחדתhard_3_3.txt",
		"הריבוע מקבילית מיוחדתhard_4_1.txt",
		"הריבוע מקבילית מיוחדתhard_4_2.txt",
		"הריבוע מקבילית מיוחדתhard_4_3.txt",
		"הריבוע מקבילית מיוחדתhard_4_4.txt",
		"חיבור וחיסורeasy_1_1.txt",
		"חיבור וחיסורeasy_2_1.txt",
		"חיבור וחיסורeasy_2_2.txt",
		"חיבור וחיסורeasy_3_1.txt",
		"חיבור וחיסורeasy_3_2.txt",
		"חיבור וחיסורeasy_3_3.txt",
		"חיבור וחיסורeasy_4_1.txt",
		"חיבור וחיסורeasy_4_2.txt",
		"חיבור וחיסורeasy_4_3.txt",
		"חיבור וחיסורeasy_4_4.txt",
		"חיבור וחיסורhard_1_1.txt",
		"חיבור וחיסורhard_2_1.txt",
		"חיבור וחיסורhard_2_2.txt",
		"חיבור וחיסורhard_3_1.txt",
		"חיבור וחיסורhard_3_2.txt",
		"חיבור וחיסורhard_3_3.txt",
		"חיבור וחיסורhard_4_1.txt",
		"חיבור וחיסורhard_4_2.txt",
		"חיבור וחיסורhard_4_3.txt",
		"חיבור וחיסורhard_4_4.txt",
		"חיבורeasy_1_1.txt",
		"חיבורeasy_2_1.txt",
		"חיבורeasy_2_2.txt",
		"חיבורeasy_3_1.txt",
		"חיבורeasy_3_2.txt",
		"חיבורeasy_3_3.txt",
		"חיבורeasy_4_1.txt",
		"חיבורeasy_4_2.txt",
		"חיבורeasy_4_3.txt",
		"חיבורeasy_4_4.txt",
		"חיבורhard_1_1.txt",
		"חיבורhard_2_1.txt",
		"חיבורhard_2_2.txt",
		"חיבורhard_3_1.txt",
		"חיבורhard_3_2.txt",
		"חיבורhard_3_3.txt",
		"חיבורhard_4_1.txt",
		"חיבורhard_4_2.txt",
		"חיבורhard_4_3.txt",
		"חיבורhard_4_4.txt",
		"חילוק במחלק דו ספרתיeasy_1_1.txt",
		"חילוק במחלק דו ספרתיeasy_2_1.txt",
		"חילוק במחלק דו ספרתיeasy_2_2.txt",
		"חילוק במחלק דו ספרתיeasy_3_1.txt",
		"חילוק במחלק דו ספרתיeasy_3_2.txt",
		"חילוק במחלק דו ספרתיeasy_3_3.txt",
		"חילוק במחלק דו ספרתיeasy_4_1.txt",
		"חילוק במחלק דו ספרתיeasy_4_2.txt",
		"חילוק במחלק דו ספרתיeasy_4_3.txt",
		"חילוק במחלק דו ספרתיeasy_4_4.txt",
		"חילוק במחלק דו ספרתיhard_1_1.txt",
		"חילוק במחלק דו ספרתיhard_2_1.txt",
		"חילוק במחלק דו ספרתיhard_2_2.txt",
		"חילוק במחלק דו ספרתיhard_3_1.txt",
		"חילוק במחלק דו ספרתיhard_3_2.txt",
		"חילוק במחלק דו ספרתיhard_3_3.txt",
		"חילוק במחלק דו ספרתיhard_4_1.txt",
		"חילוק במחלק דו ספרתיhard_4_2.txt",
		"חילוק במחלק דו ספרתיhard_4_3.txt",
		"חילוק במחלק דו ספרתיhard_4_4.txt",
		"חילוק במחלק חד ספרתיeasy_1_1.txt",
		"חילוק במחלק חד ספרתיeasy_2_1.txt",
		"חילוק במחלק חד ספרתיeasy_2_2.txt",
		"חילוק במחלק חד ספרתיeasy_3_1.txt",
		"חילוק במחלק חד ספרתיeasy_3_2.txt",
		"חילוק במחלק חד ספרתיeasy_3_3.txt",
		"חילוק במחלק חד ספרתיeasy_4_1.txt",
		"חילוק במחלק חד ספרתיeasy_4_2.txt",
		"חילוק במחלק חד ספרתיeasy_4_3.txt",
		"חילוק במחלק חד ספרתיeasy_4_4.txt",
		"חילוק במחלק חד ספרתיhard_1_1.txt",
		"חילוק במחלק חד ספרתיhard_2_1.txt",
		"חילוק במחלק חד ספרתיhard_2_2.txt",
		"חילוק במחלק חד ספרתיhard_3_1.txt",
		"חילוק במחלק חד ספרתיhard_3_2.txt",
		"חילוק במחלק חד ספרתיhard_3_3.txt",
		"חילוק במחלק חד ספרתיhard_4_1.txt",
		"חילוק במחלק חד ספרתיhard_4_2.txt",
		"חילוק במחלק חד ספרתיhard_4_3.txt",
		"חילוק במחלק חד ספרתיhard_4_4.txt",
		"חיסורeasy_1_1.txt",
		"חיסורeasy_2_1.txt",
		"חיסורeasy_2_2.txt",
		"חיסורeasy_3_1.txt",
		"חיסורeasy_3_2.txt",
		"חיסורeasy_3_3.txt",
		"חיסורeasy_4_1.txt",
		"חיסורeasy_4_2.txt",
		"חיסורeasy_4_3.txt",
		"חיסורeasy_4_4.txt",
		"חיסורhard_1_1.txt",
		"חיסורhard_2_1.txt",
		"חיסורhard_2_2.txt",
		"חיסורhard_3_1.txt",
		"חיסורhard_3_2.txt",
		"חיסורhard_3_3.txt",
		"חיסורhard_4_1.txt",
		"חיסורhard_4_2.txt",
		"חיסורhard_4_3.txt",
		"חיסורhard_4_4.txt",
		"כפלeasy_1_1.txt",
		"כפלeasy_2_1.txt",
		"כפלeasy_2_2.txt",
		"כפלeasy_3_1.txt",
		"כפלeasy_3_2.txt",
		"כפלeasy_3_3.txt",
		"כפלeasy_4_1.txt",
		"כפלeasy_4_2.txt",
		"כפלeasy_4_3.txt",
		"כפלeasy_4_4.txt",
		"כפלhard_1_1.txt",
		"כפלhard_2_1.txt",
		"כפלhard_2_2.txt",
		"כפלhard_3_1.txt",
		"כפלhard_3_2.txt",
		"כפלhard_3_3.txt",
		"כפלhard_4_1.txt",
		"כפלhard_4_2.txt",
		"כפלhard_4_3.txt",
		"כפלhard_4_4.txt",
		"מכנה משותףeasy_1_1.txt",
		"מכנה משותףeasy_2_1.txt",
		"מכנה משותףeasy_2_2.txt",
		"מכנה משותףeasy_3_1.txt",
		"מכנה משותףeasy_3_2.txt",
		"מכנה משותףeasy_3_3.txt",
		"מכנה משותףeasy_4_1.txt",
		"מכנה משותףeasy_4_2.txt",
		"מכנה משותףeasy_4_3.txt",
		"מכנה משותףeasy_4_4.txt",
		"מכנה משותףhard_1_1.txt",
		"מכנה משותףhard_2_1.txt",
		"מכנה משותףhard_2_2.txt",
		"מכנה משותףhard_3_1.txt",
		"מכנה משותףhard_3_2.txt",
		"מכנה משותףhard_3_3.txt",
		"מכנה משותףhard_4_1.txt",
		"מכנה משותףhard_4_2.txt",
		"מכנה משותףhard_4_3.txt",
		"מכנה משותףhard_4_4.txt",
		"מלבן מקבילית מיוחדתeasy_1_1.txt",
		"מלבן מקבילית מיוחדתeasy_2_1.txt",
		"מלבן מקבילית מיוחדתeasy_2_2.txt",
		"מלבן מקבילית מיוחדתeasy_3_1.txt",
		"מלבן מקבילית מיוחדתeasy_3_2.txt",
		"מלבן מקבילית מיוחדתeasy_3_3.txt",
		"מלבן מקבילית מיוחדתeasy_4_1.txt",
		"מלבן מקבילית מיוחדתeasy_4_2.txt",
		"מלבן מקבילית מיוחדתeasy_4_3.txt",
		"מלבן מקבילית מיוחדתeasy_4_4.txt",
		"מלבן מקבילית מיוחדתhard_1_1.txt",
		"מלבן מקבילית מיוחדתhard_2_1.txt",
		"מלבן מקבילית מיוחדתhard_2_2.txt",
		"מלבן מקבילית מיוחדתhard_3_1.txt",
		"מלבן מקבילית מיוחדתhard_3_2.txt",
		"מלבן מקבילית מיוחדתhard_3_3.txt",
		"מלבן מקבילית מיוחדתhard_4_1.txt",
		"מלבן מקבילית מיוחדתhard_4_2.txt",
		"מלבן מקבילית מיוחדתhard_4_3.txt",
		"מלבן מקבילית מיוחדתhard_4_4.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_1_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_2_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_2_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_3_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_3_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_3_3.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_4_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_4_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_4_3.txt",
		"ממספר עשרוני לשבר פשוט או למספרeasy_4_4.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_1_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_2_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_2_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_3_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_3_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_3_3.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_4_1.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_4_2.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_4_3.txt",
		"ממספר עשרוני לשבר פשוט או למספרhard_4_4.txt",
		"מעויין מקבילית מיוחדתeasy_1_1.txt",
		"מעויין מקבילית מיוחדתeasy_2_1.txt",
		"מעויין מקבילית מיוחדתeasy_2_2.txt",
		"מעויין מקבילית מיוחדתeasy_3_1.txt",
		"מעויין מקבילית מיוחדתeasy_3_2.txt",
		"מעויין מקבילית מיוחדתeasy_3_3.txt",
		"מעויין מקבילית מיוחדתeasy_4_1.txt",
		"מעויין מקבילית מיוחדתeasy_4_2.txt",
		"מעויין מקבילית מיוחדתeasy_4_3.txt",
		"מעויין מקבילית מיוחדתeasy_4_4.txt",
		"מעויין מקבילית מיוחדתhard_1_1.txt",
		"מעויין מקבילית מיוחדתhard_2_1.txt",
		"מעויין מקבילית מיוחדתhard_2_2.txt",
		"מעויין מקבילית מיוחדתhard_3_1.txt",
		"מעויין מקבילית מיוחדתhard_3_2.txt",
		"מעויין מקבילית מיוחדתhard_3_3.txt",
		"מעויין מקבילית מיוחדתhard_4_1.txt",
		"מעויין מקבילית מיוחדתhard_4_2.txt",
		"מעויין מקבילית מיוחדתhard_4_3.txt",
		"מעויין מקבילית מיוחדתhard_4_4.txt",
		"מקביליתeasy_1_1.txt",
		"מקביליתeasy_2_1.txt",
		"מקביליתeasy_2_2.txt",
		"מקביליתeasy_3_1.txt",
		"מקביליתeasy_3_2.txt",
		"מקביליתeasy_3_3.txt",
		"מקביליתeasy_4_1.txt",
		"מקביליתeasy_4_2.txt",
		"מקביליתeasy_4_3.txt",
		"מקביליתeasy_4_4.txt",
		"מקביליתhard_1_1.txt",
		"מקביליתhard_2_1.txt",
		"מקביליתhard_2_2.txt",
		"מקביליתhard_3_1.txt",
		"מקביליתhard_3_2.txt",
		"מקביליתhard_3_3.txt",
		"מקביליתhard_4_1.txt",
		"מקביליתhard_4_2.txt",
		"מקביליתhard_4_3.txt",
		"מקביליתhard_4_4.txt",
		"סדר פעולות חשבוןeasy_1_1.txt",
		"סדר פעולות חשבוןeasy_2_1.txt",
		"סדר פעולות חשבוןeasy_2_2.txt",
		"סדר פעולות חשבוןeasy_3_1.txt",
		"סדר פעולות חשבוןeasy_3_2.txt",
		"סדר פעולות חשבוןeasy_3_3.txt",
		"סדר פעולות חשבוןeasy_4_1.txt",
		"סדר פעולות חשבוןeasy_4_2.txt",
		"סדר פעולות חשבוןeasy_4_3.txt",
		"סדר פעולות חשבוןeasy_4_4.txt",
		"סדר פעולות חשבוןhard_1_1.txt",
		"סדר פעולות חשבוןhard_2_1.txt",
		"סדר פעולות חשבוןhard_2_2.txt",
		"סדר פעולות חשבוןhard_3_1.txt",
		"סדר פעולות חשבוןhard_3_2.txt",
		"סדר פעולות חשבוןhard_3_3.txt",
		"סדר פעולות חשבוןhard_4_1.txt",
		"סדר פעולות חשבוןhard_4_2.txt",
		"סדר פעולות חשבוןhard_4_3.txt",
		"סדר פעולות חשבוןhard_4_4.txt",
		"שטח מצולעeasy_1_1.txt",
		"שטח מצולעeasy_2_1.txt",
		"שטח מצולעeasy_2_2.txt",
		"שטח מצולעeasy_3_1.txt",
		"שטח מצולעeasy_3_2.txt",
		"שטח מצולעeasy_3_3.txt",
		"שטח מצולעeasy_4_1.txt",
		"שטח מצולעeasy_4_2.txt",
		"שטח מצולעeasy_4_3.txt",
		"שטח מצולעeasy_4_4.txt",
		"שטח מצולעhard_1_1.txt",
		"שטח מצולעhard_2_1.txt",
		"שטח מצולעhard_2_2.txt",
		"שטח מצולעhard_3_1.txt",
		"שטח מצולעhard_3_2.txt",
		"שטח מצולעhard_3_3.txt",
		"שטח מצולעhard_4_1.txt",
		"שטח מצולעhard_4_2.txt",
		"שטח מצולעhard_4_3.txt",
		"שטח מצולעhard_4_4.txt",
		"שטח משולשeasy_1_1.txt",
		"שטח משולשeasy_2_1.txt",
		"שטח משולשeasy_2_2.txt",
		"שטח משולשeasy_3_1.txt",
		"שטח משולשeasy_3_2.txt",
		"שטח משולשeasy_3_3.txt",
		"שטח משולשeasy_4_1.txt",
		"שטח משולשeasy_4_2.txt",
		"שטח משולשeasy_4_3.txt",
		"שטח משולשeasy_4_4.txt",
		"שטח משולשhard_1_1.txt",
		"שטח משולשhard_2_1.txt",
		"שטח משולשhard_2_2.txt",
		"שטח משולשhard_3_1.txt",
		"שטח משולשhard_3_2.txt",
		"שטח משולשhard_3_3.txt",
		"שטח משולשhard_4_1.txt",
		"שטח משולשhard_4_2.txt",
		"שטח משולשhard_4_3.txt",
		"שטח משולשhard_4_4.txt",
		"pathfind.js"
	]
}